### ISSUE TITLE
Figure 2 should be updated to include HDR10+ Metadata OBU

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-hdr10plus#21]
Figure 2 should be updated as it only documents the structure of a stream without HDR10+ metadata OBUs. Maybe a Figure 3 could be added to show where the HDR10+ metadata OBUs shall be inserted.

**Comment by quantizationbit** [comment]
[Bitstream split in TUs by temporal delimiters_Image.docx](https://github.com/AOMediaCodec/av1-hdr10plus/files/8732840/Bitstream.split.in.TUs.by.temporal.delimiters_Image.docx)

Updated figure 2

**Comment by cconcolato** [comment]
Updated document as discussed in meeting [Bitstream.split.in.TUs.by.temporal.delimiters_Image_CC.docx](https://github.com/AOMediaCodec/av1-hdr10plus/files/8756940/Bitstream.split.in.TUs.by.temporal.delimiters_Image_CC.docx)

Agreement to close this issue after the image in the spec is updated.

**Comment by cconcolato** [comment]
Closed with #33
