### ISSUE TITLE
cdm4 brand should vs shall

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/av1-hdr10plus#23]
Currently there is only a should for `cdm4` brand in [the spec](https://aomediacodec.github.io/av1-hdr10plus/#isobmff-constraints). 

And even the [Sample AV1 Encoded HDR10+ File](https://hdr10plus.org/av1_sample/HDR10_SIZZLE_PLUS_UP-FINAL_02_AV1.mp4) provided by Samsung has no `cdm4` brand in it. 

It looks like the presence of this brand is the only way to figure out if .mp4 file has HDR10+ in it (without parsing samples and T.35 metadata OBUs).

Why is there a should in av1-hdr10plus spec, when in the SCTE spec (referenced in CTA-5001, referenced in av1-hdr10plus) `cdm4` shall be in the ftyp?

**Comment by quantizationbit** [comment]
cdm4 is not used in legacy AV1 content and thus needs to be optional.  HDR10+ suppport may be indicated at manifest level using Supplemental Property as already included in the specification.  SCTE for their particular HEVC use case chose to make it mandatory but it is not mandatory for HDR10+ receivers and displays supporting AV1.

**Comment by podborski** [comment]
Ok for DASH manifest. But what about local files? There seems to be no easy way to figure out if the track is an HDR10+ track. MDCV seems to be used as an indicator but it's not perfect as we still don't know if the track has dynamic metadata in it without looking into the samples, right?

**Comment by cconcolato** [comment]
The use case is to be able to tell if the file (and which track) contains HDR10+ without having to sniff/parse the sample data. The brand could be absent or the file could have multiple video tracks. In those cases, it is currently hard to tell if a track is using HDR10+.

MPEG is working on the signaling of the presence of T.35 messages, with a sample group. However sample groups could only be used in fragments and not in the initialization header. Maybe we need to recommend setting this sample group in the header. 

An alternative could be to recommend/mandate the presence of the TrackTypeBox with the cdm4 brand.

An alternative not depending on MPEG could be to have signaling in the sample description. A box that would be ignored by old parser. What would the box contain? Empty?

The group will study the alternatives.

**Comment by cconcolato** [comment]
The group thinks that for publication of v1, we still keep the "should" but we continue studying the question of how to signal presence of HDR10+ data and may add that in a future version.

**Comment by quantizationbit** [comment]
See above (leaving as should)
