### ISSUE TITLE
Update section 2.2 to indicate that MDCV is mandatory

### ISSUE THREAD

**Issue by quantizationbit** [AOMediaCodec/av1-hdr10plus#25]
Need to update this sentance in section 2.2:

"HDR10 Static Metadata (defined as MDCV, MaxCLL and MaxFALL) may be present.”

While HDR10+ does not need these parameters in the outside standards: ATSC, SCTE, DVB they were written that MDCV is mandatory and MaxCLL/FALL are optional.  We will sync this.

**Comment by cconcolato** [comment]
I assume this is at the elementary stream level, right? What about the ISOBMFF level? Is the `mdcv` box mandatory? 

The current version of AV1-ISOBMFF says:
>For sample entries corresponding to HDR content, the MasteringDisplayColourVolumeBox [mdcv](https://www.iso.org/standard/68960.html#) and ContentLightLevelBox [clli](https://www.iso.org/standard/68960.html#) SHOULD be present, and their values SHALL match the values contained in the [Metadata OBUs](https://aomediacodec.github.io/av1-spec/av1-spec.pdf#page=46) of type METADATA_TYPE_HDR_CLL and METADATA_TYPE_HDR_MDCV, if present (in the configOBUs or in the samples).

The AV1-HDR10+ spec says:
> For formats that use the [AV1CodecConfigurationRecord](https://aomediacodec.github.io/av1-hdr10plus/#biblio-av1-isobmff) when storing AV1 streams (e.g. ISOBMFF and MPEG-2 TS), [HDR10+ Metadata OBUs](https://aomediacodec.github.io/av1-hdr10plus/#hdr10-metadata-obu) shall not be present in the [configOBUs](https://aomediacodec.github.io/av1-hdr10plus/#biblio-av1-isobmff) field of the [AV1CodecConfigurationRecord](https://aomediacodec.github.io/av1-hdr10plus/#biblio-av1-isobmff).

It's also not clear if:
a) the MDCV/CLLI OBUs are replaced by their box versions upon packaging and then the box versions get replaced by the OBU versions upon unpackaging, i.e. the MDCV/CLLI OBUs are not present in the elementary stream when stored in MP4.
b) both the MDCV OBU and the box are used (and similarly for CLLI OBU and box).

**Comment by quantizationbit** [comment]
MDCV is mandatory in HEVC elementary streams for DVB, ATSC, SCTE when either or both HDR10+/DV is used.  CLL/FALL is always optional.

MDCV can be optional for HDR10+ so we made it optional here because we can not anticipate all possible uses (e.g. cloud gaming) where maybe the service provider does not have or does not want to provide it. Also there may be cases where a service provider chooses to have it to align with these other systems.  

We reccommend against making this change for these reasons.

**Comment by podborski** [comment]
According to `HDR10+ Technical Specification |Part 1: Metadata and Devices | Version 1.4 | January 5, 2020` from HDR10+ Technologies, LLC the mdcv is mandatory.

> HDR10+ Video Stream **SHALL** comply with following requirements
> ...
> - Metadata (Required):
>   - Mastering Display Color Volume Metadata [7]
> ...

In addition to that, there seems to be no other metadata on the systems level which allows to figure out if the file has HDR10(+) metadata in it or not.

**Comment by quantizationbit** [comment]
#29

**Comment by cconcolato** [comment]
Closed with #34
