### ISSUE TITLE
Use of configOBUs

### ISSUE THREAD

**Issue by cconcolato** [AOMediaCodec/av1-hdr10plus#3]
https://aomediacodec.github.io/av1-isobmff/#av1codecconfigurationbox-semantics indicates:
> NOTE: The configOBUs field is expected to contain only one Sequence Header OBU and zero or more Metadata OBUs when applicable to all the associated samples.

A question is: should we allow HDR10+ metadata in the configOBUs array?
Given that HDR10+ metadata is supposed to change at every sample, I don't think it makes sense to have it in the configOBUs array.

So the question is rather: should we forbid the use of HDR+ metadata in the configOBUs array? 
I would suggest:
> HDR10+ Metadata OBUs should not be present in the configOBUs field of the AV1CodecConfigurationRecord.

**Comment by quantizationbit** [comment]
Our engineer reviewed the proposal and offered this line of text to address MP4/MPEG2:  For MP4 Files and MPEG2 Transport cases HDR10+ metadata OBUs, which are dynamic, Shall should not be present in the configOBUs in AV1CodecConfiguration record.

**Comment by cconcolato** [comment]
I recommend changing the title of Section 3 to "Storage and Transport considerations" and then having no subsections and just one paragraph saying:
> For formats that use the AV1CodecConfigurationRecord (e.g. ISOBMFF and MPEG-2 TS), HDR10+ Metadata OBUs shall not be present in the configOBUs field of the record.
