### ISSUE TITLE
Conformance section reference to RFC 2119

### ISSUE THREAD

**Issue by podborski** [AOMediaCodec/av1-hdr10plus#41]
Our bikeshed template currently adds the reference to the RFC2119 which points to https://datatracker.ietf.org/doc/html/rfc2119 should it be pointing to https://www.ietf.org/rfc/rfc2119.txt instead?

Also the name of the specification should be changed. Currently it is:

> [RFC2119]
> S. Bradner. [Key words for use in RFCs to Indicate Requirement Levels](https://datatracker.ietf.org/doc/html/rfc2119). March 1997. Best Current Practice. URL: https://datatracker.ietf.org/doc/html/rfc2119

But it should be:
> [RFC2119] 
> IETF RFC 2119, Key words for use in RFCs to Indicate Requirement Levels, S. Bradner, March 1997. Best Current Practice. URL: https://www.ietf.org/rfc/rfc2119.txt

**Comment by podborski** [comment]
@cconcolato do we need to update the bikeshed template for this?

**Comment by cconcolato** [comment]
I don't see the value in updating the URL or the template. Why?

**Comment by podborski** [comment]
Im not so much familiar with IETF. Is the datatracker link a link to the stable version of the specification?
